development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://odbfqpnibmtelf:42e6e8a636e4ade86c4d3ad308a2f3c71924507cd729a114134239c6cd57e61d@ec2-50-17-206-214.compute-1.amazonaws.com:5432/d129lsomlg7a62
  channel_prefix: nameofapp_production
